name: coverage
on:
  push:
    branches:  [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Build
        run: npm install -g yarn & yarn install
      - name: Create Test Coverage
        run: yarn test-coverage
      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
