name: deploy
on:
  release:
    types: [published]
jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: npm install -g yarn & yarn install
      - name: Test
        run: yarn test-all
  publish:
    needs: run-all-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Build
        run: npm install -g yarn & yarn install
      - name: Publish
        run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }} & publish
